### ISSUE TITLE
How to disable tslint?

### ISSUE THREAD

**Issue by azu** [wmonk/create-react-app-typescript#133] opened 2017-08-06 04:08 UTC
### Description

Currently, [tslint.json](https://github.com/wmonk/create-react-app-typescript/blob/master/packages/react-scripts/template/tslint.json "tslint.json") contains style-specific rules.

- indent
- whitespace
- quotemark

etc...

I've tried to use `react-scripts-ts` and I've feel frustrated to following lint error

```
./src/XXX.ts
[12, 34]: " should be '
[12, 50]: " should be '
[13, 33]: " should be '
[25, 60]: " should be '
... a lot of lint errors..
```

### Expected behavior

- Relax tslint rule
- Or, can you provide disabling way?

It is difficult that provide fundamental solution, I think.

### Actual behavior

Report style error on `npm start`

### Related

- [disable eslint · Issue #2157 · facebookincubator/create-react-app](https://github.com/facebookincubator/create-react-app/issues/2157 "disable eslint · Issue #2157 · facebookincubator/create-react-app")
- https://github.com/facebookincubator/create-react-app/blob/master/packages/eslint-config-react-app/index.js

**Comment by foxylion** [comment] 2017-08-06 11:34
I think this should be possible by creating an empty `tslint.json` in your project root. This will force tslint to disable all linters.

**Comment by azu** [comment] 2017-08-06 11:56
@foxylion Oh, Thanks.
It work fine 👍 

```shell-session
$ cat tslint.json
{
    "rules":{
    }
}

$ yarn start
Starting the development server...

No valid rules have been specified
...
```

I've been confused about it, because **create-react-app** said that


> Note that even if you edit your .eslintrc file further, these changes will only affect the editor integration. They won’t affect the terminal and in-browser lint output. This is because Create React App intentionally provides a minimal set of rules that find common mistakes.  
> -- https://github.com/facebookincubator/create-react-app/blob/e12d053c273037c5ec75971ddcd117b3e9858cdf/packages/react-scripts/template/README.md#displaying-lint-output-in-the-editor

**Comment by wmonk** [comment] 2017-08-07 13:42
@foxylion is this all solved now? If so please can you close this issue.

**Closed** 2017-08-07 14:12 UTC
Labels: waiting-on-feedback

**Comment by bestwestern** [comment] 2017-10-31 15:35
Please open this again: It wont compile because of unused var
![image](https://user-images.githubusercontent.com/3617433/32232911-702cb264-be59-11e7-9814-0080896c03c0.png)

**Comment by 1oginov** [comment] 2017-11-18 14:16
@bestwestern you're right, I've also removed all rules from `tslint.json`, removed `noUnusedLocals` from `tsconfig.json` and it keeps failing with `error TS2552: Cannot find name...`

**Comment by YagoLopez** [comment] 2017-12-02 16:59
Yeah It would be great disable tslint during development. App compilation would be faster without lint check. In my opinion ideal situation would be lint the code voluntarily when you want, not each recompilation.

**Comment by 1oginov** [comment] 2017-12-02 20:21
For example, in my case I've wanted to develop an electron app with the help of create-react-app-typescript, but I've needed to do some things that TSLint doesn't want me to do, like `window.require()` to prevent `require()` to be handled by webpack, since it is the only way to get access to the electron remote process.

**Comment by YagoLopez** [comment] 2017-12-02 20:36
@1oginov  I manged to disable tslint in my environment (react + typescript). In my case deleting all rules in `tslint.json` and leaving a void `{}` object in the file did it. Hope that helps.

**Comment by Ebuall** [comment] 2018-03-22 20:00
Is there a way to disable it completely, while keeping config? 
I think it should live in IDE and only IDE should run it.
I don't want waste PC resources and don't think linter should prevent compilation during development.

**Comment by janacm** [comment] 2018-03-29 16:02
Is there a way to make the linter wait until I'm done typing before yelling at me for semi colon errors?

**Comment by TeoTN** [comment] 2018-04-02 17:29
Why to waste time on linting on recompile when you can spare some cpu power on bitcoin mining? Has anyone figured out a way how to kill the linter completely?

**Comment by rock007** [comment] 2018-04-24 03:42
hi,it can't disable ,but you can do this:
![image](https://user-images.githubusercontent.com/2245512/39164922-835a9ce0-47b4-11e8-846c-97affbabed21.png)

exclude all file you code

**Comment by gunn4r** [comment] 2018-04-25 17:31
Any updates on this? The internal linter is really wrecking our dev process. We run tslint in our IDEs and on commits / CI. Having a hidden lint config that we can't change is brutal. Any solutions?

**Comment by maracuja-juice** [comment] 2018-04-25 18:25
@gunn4r you can change your tslint according to your needs. Never had any issues with that.

**Comment by dadayada** [comment] 2018-05-02 12:29
@maracuja-juice linter should not affect compilation. I want the app to work but I also want to see linter`s warnings.

**Comment by elektronik2k5** [comment] 2018-05-02 15:47
@dadayada, not necessarily. It really depends on your use case and how strict you want lint to be enforced.
I for example would prefer to have the linter fail the compilation. You think differently - and that's ok! If you prefer strict linter's feedback in your editor/command line but still compile, you can do that: make the default lenient (to not affect compilation) and extend it with a stricter conf, which your editor/cli will invoke.

What I'm saying is that there's no single right or wrong way to use the linter - because different people use the same tool in different ways for different purposes. We can't cater to all of them with a single default. We can only decide on a reasonable one, which should serve most people.

I'm in favor of a strict default and a well documented way to override it.

**Comment by louisptremblay** [comment] 2018-05-16 15:28
To implement suggested workarounds in VS Code:
-Rename `tslint.json` to `tslint.ide.json`
-Create `tslint.json` with empty `{}` inside
-Add line to VS Code settings: `"tslint.configFile": "./tslint.ide.json"`

**Comment by tomjakubowski** [comment] 2018-05-31 18:41
My workaround is like the above, but reversed:

* Add `"defaultSeverity": "warn"` to `tslint.json`
* Create a new `tslint.prod.json`, which extends `"./tslint.json"` but overrides `"defaultSeverity": "error"`
* Add a `lint` script to `package.json` which runs `tslint --project . --config tslint.prod.json`.

CI runs `npm run lint` (so CI catches linter errors) followed by `npm run build`. I don't think I can configure which tslint config file `npm run build` uses without ejecting. That means, unfortunately, in CI tslint runs twice: first for `npm run lint` (with `"defaultSeverity:" "error"`), then the usual tslint step as part of `react-scripts-ts build` (with `"defaultSeverity": "warning"`). But that's OK with me.

**Comment by YagoLopez** [comment] 2018-06-03 15:03
If you are using Webstorm, when you open the project the **event log window** says:

> TSLint is enabled: config file is in the project.
> 				 **[Disable TSLint](url)**

Supposedly clicking "Disable TsLint" allows deactivation. Not confirmed.

**Comment by gryzzly** [comment] 2018-06-12 12:55
It is unbelievable that there is no workaround for this provided by the tool authors. 

Many of us deal with existing projects where we didn’t have a way to choose the tooling and have to deal with what’s there.

Please provide an official way to disable TSLint in development and have it only run within IDE.

**Comment by carpben** [comment] 2018-11-27 14:38
@gryzzly This is an open source project, and the authors don't get payed. There is no reason to point blame towards or demand from the authors. I am using this project just like you and was quite surprised to read your comment.

**Comment by carpben** [comment] 2018-11-27 14:50
@wmonk  I do wonder if such a strict set of rules as default is the right way to go for such a package, which is used and presents itself as Typescript's "create-react-app". 
From what I remember create-react-app itself comes with a very basic set of linting rules as default.
