### ISSUE TITLE
The batch file cannot be found error when we run npm run eject

### ISSUE THREAD

**Issue by jquintozamora** [wmonk/create-react-app-typescript#67] opened 2017-05-22 15:36 UTC
### Actual behavior

When ejecting the project, I got an error like:
The batch file cannot be found error
![image](https://cloud.githubusercontent.com/assets/12530031/26316508/615db430-3f0c-11e7-9ab9-565632203461.png)

### Environment

Run these commands in the project folder and fill in their results:
`node -v`:  7.9.0
`npm -v`:  4.5.0
Operating system: Windows 8

### Reproducible Demo

npm install -g create-react-app
create-react-app my-app --scripts-version=react-scripts-ts
cd my-app/
npm run eject

**Comment by wmonk** [comment] 2017-05-22 16:38
I'm afraid I can't reproduce this, as I don't have a windows machine. I assume as it's printed the `Ejected successfully!` message it must be an `inquirer` issue.

**Comment by ttrunck** [comment] 2017-05-22 21:52
I'm not able to reproduce it on Windows 10. But it seems that your eject is done using a quite old version of Yarn (and not using npm). Could this be the issue, did you tried to update Yarn?

**Comment by wmonk** [comment] 2017-06-15 09:10
Closing as this hasn't been updated in a while.

**Closed by wmonk** 2017-06-15 09:10 UTC
Labels: help wanted

**Comment by gaearon** [comment] 2018-01-15 20:27
If you're curious about why this was happening: https://github.com/facebookincubator/create-react-app/pull/3806#issuecomment-357781035

We disabled Yarn during eject so it stopped, but there probably is some correct solution here.

**Comment by NotAdrian** [comment] 2018-06-01 15:47
I just looked into it, after some hours I found the reason and created a Comment on another issue here, its pretty much a operating system (Windows < 10) issue. For a more detailed report I'm just going to leave the link from my other comment here: [Click me](https://github.com/react-community/create-react-native-app/issues/367#issuecomment-393919935)

**Comment by fanam** [comment] 2018-07-21 09:01
Instead of using "npm run eject"
use "npm install -g exp" & "exp detach"
And edit varibles in app.json file https://docs.expo.io/versions/latest/workflow/configuration
