### ISSUE TITLE
Dynamic import not working

### ISSUE THREAD

**Issue by KatSick** [wmonk/create-react-app-typescript#90] opened 2017-06-23 08:59 UTC
### Description
Dynamic import not split bundle into chunks.

### Expected behavior

When using import('./component') inside some callback webpack should extract it to separate bundle.

### Actual behavior

It always loads full bundle

### Environment

1. `npm ls react-scripts-ts` (if you haven’t ejected): react-scripts-ts@2.2.0
2. `node -v`: v6.11.0
3. `npm -v`: 3.10.10

Then, specify:

1. Operating system: Mac OS Sierra
2. Browser and version: Chrome latest

**Comment by codeaid** [comment] 2017-07-06 10:18
I have the same problem. I got it working by changing extension of the file containing my async component import statements from `*.ts` to `*.js`.

Looks like it's some configuration issue somewhere.

**Comment by rohmanhm** [comment] 2017-07-08 11:36
`react-script-ts` not yet support `import()` since it stuck with **Typescript v2.3.3**.
Dynamic import available in **Typescript v2.4.***. For a while just use `require.ensure()` to replace `import()`

**Comment by wmonk** [comment] 2017-07-13 08:19
We have shipped 2.4 now, so this should be working. Please update so I can close this issue.

**Comment by nicolaserny** [comment] 2017-07-24 08:29
Dynamic import works fine with the latest version.
But you have to update the tsconfig.json file to make it work:
Set module to esnext (instead of commonjs)

**Comment by wmonk** [comment] 2017-07-24 09:05
@nicolaserny can you open a PR with the necessary updates to tsconfig?

**Comment by codeaid** [comment] 2017-07-24 09:21
It's worked for me without changing `module` for a long time. I don't think that's needed.

**Comment by nicolaserny** [comment] 2017-07-24 10:04
I've just created a basic example with a project create create react app ts + react router (see attached document).
with commonjs module:
File sizes after gzip:

  60.42 KB  build/static/js/main.6b8b3e4e.js
  289 B     build/static/css/main.9a0fe4f1.css

with esnext module:
File sizes after gzip:

  60.53 KB (+106 B)  build/static/js/main.1319f34a.js
  289 B              build/static/css/main.9a0fe4f1.css
  230 B              build/static/js/homejs.5a764d30.chunk.js
  227 B              build/static/js/otherjs.4291caf7.chunk.js

[test-code-splitting.zip](https://github.com/wmonk/create-react-app-typescript/files/1169468/test-code-splitting.zip)

**Closed** 2017-07-27 12:45 UTC
Labels: fixed, waiting-on-feedback

**Comment by KatSick** [comment] 2017-08-08 09:29
for me with "commonjs" module type import not worked

**Comment by JLarky** [comment] 2017-10-15 03:37
I can confirm that it doesn't work with `commonjs`, it clearly states in https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html 

> using this new feature with the esnext module target

**Comment by rolandjitsu** [comment] 2018-05-27 09:54
@wmonk I'm still having this issue when running tests. Building and running the app works fine with dynamic imports, but not when I run `react-scripts-ts test`.

Do you know why could this happen?
