### ISSUE TITLE
TS2304: Cannot find name 'process'.

### ISSUE THREAD

**Issue by goldenbearkin** [wmonk/create-react-app-typescript#93] opened 2017-06-27 19:34 UTC
````
npm install -g create-react-app
create-react-app react-typescript --scripts-version=react-scripts-ts
cd react-typescript
npm start
````
I got this right away.
````
./src/registerServiceWorker.ts
(12,7): error TS2304: Cannot find name 'process'.
````

**Comment by wmonk** [comment] 2017-06-27 19:39
Hmm are all the typing installed? Think process should come from `@types/node`.

**Comment by goldenbearkin** [comment] 2017-06-27 19:45
I think so. This is my package.json
````json
{
  "name": "react-typescript",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@types/jest": "^20.0.2",
    "@types/node": "^8.0.4",
    "@types/react": "^15.0.33",
    "@types/react-dom": "^15.5.1",
    "react": "^15.6.1",
    "react-dom": "^15.6.1"
  },
  "devDependencies": {
    "react-scripts-ts": "2.3.1"
  },
  "scripts": {
    "start": "react-scripts-ts start",
    "build": "react-scripts-ts build",
    "test": "react-scripts-ts test --env=jsdom",
    "eject": "react-scripts-ts eject"
  }
}
````

**Comment by wmonk** [comment] 2017-06-27 19:46
Can you do `npm ls --depth=0`

**Comment by goldenbearkin** [comment] 2017-06-27 19:50
sure.
````
➜  react-typescript npm ls --depth=0
react-typescript@0.1.0 /development/github/moussypad/react-typescript
├── @types/jest@20.0.2
├── @types/node@8.0.4
├── @types/react@15.0.33
├── @types/react-dom@15.5.1
├── node-pre-gyp@0.6.36 extraneous
├── react@15.6.1
├── react-dom@15.6.1
└── react-scripts-ts@2.3.1

npm ERR! extraneous: node-pre-gyp@0.6.36 /development/github/moussypad/react-typescript/node_modules/node-pre-gyp
````

**Comment by wmonk** [comment] 2017-06-27 19:58
Just tested and this is indeed not working. See there was a new release of `@types/node` 6 hours ago - so feel it might be related to that.

**Comment by seyaobey** [comment] 2017-06-27 19:59
+1 Same problem here since 3 hours ago

**Comment by wmonk** [comment] 2017-06-27 20:06
Also `typescript@4` was released earlier.

**Comment by wmonk** [comment] 2017-06-27 20:08
Yup `typescript@2.4.x` is the culprit. I will push a fix pinning to `2.3.x`

**Comment by seyaobey** [comment] 2017-06-27 20:09
@wmonk great job by the way! I just discovered this tool a few days ago. It has boosted my productivity...

**Comment by wmonk** [comment] 2017-06-27 20:22
[Once these go green](https://travis-ci.org/wmonk/create-react-app-typescript/builds/247678564) I will publish!

**Comment by wmonk** [comment] 2017-06-27 20:32
Fixed in `2.3.2`, get from npm now! If you need to update just, `npm i react-scripts-ts@latest` inside your created app.

**Closed by wmonk** 2017-06-27 20:32 UTC
Labels: bug, help wanted

**Comment by micapam** [comment] 2018-06-01 00:51
I'm seeing this with typescript 2.8.3 and @types/node 10.1.3

**Comment by ulmanA** [comment] 2018-06-13 10:05
I had that issue and the root cause was from my tsconfig.json
adding `"node"` to list `"compilerOptions"."types"` solve the issue.

**Comment by russell-osu** [comment] 2018-07-03 15:01
Thanks. Adding "node" to list "compilerOptions"."types" also solved the issue for me. `node`
